scanner:
  scanDelay: 100
  threadCount: 5
  scanPath: C:\Users\Ali_Al-Iusefi\Desktop\Git\ESM\Task_5\jsoncertificates
  errorPath: C:\Users\Ali_Al-Iusefi\Desktop\Git\ESM\Task_5\errorjsoncertificates

